# Generated by Django 5.0.11 on 2025-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_profile_picture_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
