services:
  docs:
    image: e_commerce_local_docs
    container_name: e_commerce_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./e_commerce:/app/e_commerce:z
    ports:
      - '9000:9000'
    command: /start-docs
